#! /bin/bash
#
# uw-client        Start/Stop the uw-client daemon
#
# chkconfig: 2345 90 60
# description: uw-client accepts requests from pam modules
#              and reports user information to uw-server
# processname: uw-client.pl
# config: /etc/userwatch/uw-client.conf
# pidfile: /var/run/userwatch/uw-client.pid

RETVAL=0
PROGRAM=/usr/share/userwatch/daemons/uw-client.pl
PIDFILE=/var/run/userwatch/uw-client.pid
prog="uw-client"

. /etc/init.d/functions

start() {
    echo -n $"Starting $prog: "
    daemon $PROGRAM && success || failure
    RETVAL=$?
    echo
}

stop() {
    echo -n $"Stopping $prog: "
    if [ -f $PIDFILE ]; then
        PID=`< $PIDFILE`
        kill -TERM $PID
        usleep 100000
        kill -0 $PID 2>/dev/null && kill -KILL $PID
        pkill -KILL `basename $PROGRAM`
        success $"Stopping $prog"
    else
        failure $"Stopping $prog"
    fi
    RETVAL=$?
    echo
}	

reload() {
    echo -n $"Reloading $prog: "
    if [ -f $PIDFILE ]; then
        kill -HUP `< $PIDFILE`
    else
        failure $"Reloading $prog"
    fi
    RETVAL=$?
    echo
}	

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart)
    stop
    start
    ;;
  reload)
    reload
    ;;
  status)
    if [ -f $PIDFILE ]; then
        echo "$prog running (`< $PIDFILE`)"
    else
        echo "$prog stopped"
    fi
	;;
  condrestart)
    if [ -f $PIDFILE ]; then
        stop
        start
    fi
    ;;
  *)
    echo $"Usage: $0 {start|stop|status|reload|restart|condrestart}"
    RETVAL=3
    ;;
esac
exit $RETVAL

