#! /bin/bash
#
# uw-server        Start/Stop the uw-server daemon
#
# chkconfig: 2345 90 60
# description: uw-server handles login/logout requests from uw-client
#              daemons on client machines, manages relevant iptable chains,
#              polls statistics from openvpn and maintains stats database.
# processname: uw-server.pl
# config: /etc/userwatch/uw-server.conf
# pidfile: /var/run/userwatch/uw-server.pid

RETVAL=0
PROGRAM=/usr/share/userwatch/daemons/uw-server.pl
PIDFILE=/var/run/userwatch/uw-server.pid
prog="uw-server"

. /etc/init.d/functions

start() {
    echo -n $"Starting $prog: "
    daemon $PROGRAM && success || failure
    RETVAL=$?
    echo
}

stop() {
    echo -n $"Stopping $prog: "
    if [ -f $PIDFILE ]; then
        PID=`< $PIDFILE`
        kill -TERM $PID
        usleep 100000
        kill -0 $PID 2>/dev/null && kill -KILL $PID
        pkill -KILL `basename $PROGRAM`
        success $"Stopping $prog"
    else
        failure $"Stopping $prog"
    fi
    RETVAL=$?
    echo
}	

reload() {
    echo -n $"Reloading $prog: "
    if [ -f $PIDFILE ]; then
        kill -HUP `< $PIDFILE`
    else
        failure $"Reloading $prog"
    fi
    RETVAL=$?
    echo
}	

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart)
    stop
    start
    ;;
  reload)
    reload
    ;;
  status)
    if [ -f $PIDFILE ]; then
        echo "$prog running (`< $PIDFILE`)"
    else
        echo "$prog stopped"
    fi
	;;
  condrestart)
    if [ -f $PIDFILE ]; then
        stop
        start
    fi
    ;;
  iptables)
    if [ -f $PIDFILE ]; then
        kill -USR1 `< $PIDFILE`
        echo "$prog refreshing iptables"
    else
        echo "$prog stopped"
    fi
    ;;
  *)
    echo $"Usage: $0 {start|stop|status|reload|restart|condrestart|iptables}"
    RETVAL=3
    ;;
esac
exit $RETVAL

